[package]
name = "CapyShell"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.14.1", features = ["renderer-software"] }
spell-framework = "1.0.0"
sysinfo = "0.32"
chrono = "0.4"
hyprland = "0.4.0-beta.3"
battery = "0.7"
tokio = { version = "1", features = ["rt", "sync", "time"] }
zbus = "4"
futures-util = "0.3"
crossbeam-channel = "0.5"

[build-dependencies]
slint-build = "1.14.1"

[patch.crates-io]
slint = { git = "https://github.com/slint-ui/slint" }
slint-build = { git = "https://github.com/slint-ui/slint" }
i-slint-core = { git = "https://github.com/slint-ui/slint" }
i-slint-renderer-skia = { git = "https://github.com/slint-ui/slint" }
spell-framework = { git = "https://github.com/VimYoung/Spell" }
