[package]
name = "capy-mpris"
version = "0.1.0"
edition = "2024"

[dependencies]
zbus = "4"
futures-util = "0.3"
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
log = "0.4"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
